name: Check for files that should not be edited

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'reference/ams-configuration.md'
      - 'reference/cmd-ref/amc/*.md'
      - 'reference/cmd-ref/appliance/*.md'
  pull_request:
    paths:
      - 'reference/ams-configuration.md'
      - 'reference/cmd-ref/amc/*.md'
      - 'reference/cmd-ref/appliance/*.md'

jobs:
  check:
    name: Fail
    runs-on: ubuntu-latest
    steps:
      - name: Print error
        run: echo "::error file=reference/ams-configuration.md::Never edit reference/ams-configuration.md manually - edit reference/ams-configuration.tmpl.md or reference/ams-configuration.yaml instead!"

      - name: Exit
        run: exit 1