name: Generate and commit AMS configuration doc

on:
  push:
    paths:
      - 'reference/ams-configuration.tmpl.md'
      - 'reference/ams-configuration.yaml'
  pull_request:
    paths:
      - 'reference/ams-configuration.tmpl.md'
      - 'reference/ams-configuration.yaml'

jobs:
  generate:
    name: Generate and (maybe) commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate Markdown file
        run: python scripts/generate-ams-config.py

      - name: Show Markdown file
        run: cat reference/ams-configuration.md

      - name: Commit changes
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Generate AMS configuration doc'
          add: 'reference/ams-configuration.md'
